Langchain Dependency Bug Fix: group checkpoint-postgres package with databricks-ai-bridge[memory] (#224)
With the newly added `langgraph-checkpoint-postgres>=2.0.0` dependency to langchain, customers are seeing error when `psycopg[binary,pool]>=3.1` is not installed:

```
mlflow.exceptions.MlflowException: Failed to import code model from /model/agent.py. Error: no pq wrapper available.
```

We need to bundle "langgraph-checkpoint-postgres>=2.0.0" and  "psycopg[binary,pool]>=3.1" together - this pr adds them as an optional dep of databricks-langchain package so they are only installed when user wants to access memory features

testing via notebook:

without [memory]: https://eng-ml-inference.staging.cloud.databricks.com/editor/notebooks/657935421316087?o=1653573648247579#command/657935421316094 

can import but not instantiate:
<img width="1358" height="1183" alt="image" src="https://github.com/user-attachments/assets/0e13cdc9-944a-4a63-9ca3-74dfa9a4a2e4" />

with [memory]: https://eng-ml-inference.staging.cloud.databricks.com/editor/notebooks/657935421316132?o=1653573648247579
can import and instantiate:
<img width="1335" height="1125" alt="image" src="https://github.com/user-attachments/assets/95769669-4221-44a1-b8b5-5cc31bb826d8" />

confirmed was able to spin up agent with original mas notebook dependency issue